# Generated by Django 4.2 on 2023-04-14 02:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posting', '0011_alter_postingmodel_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingmodel',
            name='author',
            field=models.ForeignKey(on_delete=models.SET('탈퇴한 이용자'), related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
